const safeQuerySelector=(selector)=>document.querySelector(selector);const safeQuerySelectorAll=(selector)=>document.querySelectorAll(selector);function initMobileMenu(){const navLinks=safeQuerySelectorAll(".nav-menu .nav-fil");const menuOpenBtn=safeQuerySelector(".menu-toggle");const menuCloseBtn=safeQuerySelector(".close-menu");const toggleMobileMenu=()=>{document.body.classList.toggle("show-mobile-menu")};if(menuOpenBtn)menuOpenBtn.addEventListener("click",toggleMobileMenu);if(menuCloseBtn)menuCloseBtn.addEventListener("click",toggleMobileMenu);navLinks.forEach(link=>{link.addEventListener("click",()=>{document.body.classList.remove("show-mobile-menu")})})}
function initDropdown(){const dropdownBtn=safeQuerySelector(".dropdown-btn");const dropdownMenu=safeQuerySelector(".dropdown-content");if(dropdownBtn&&dropdownMenu){dropdownBtn.addEventListener("click",(e)=>{e.preventDefault();dropdownMenu.classList.toggle("show")});window.addEventListener("click",(e)=>{if(!e.target.matches('.dropdown-btn')){dropdownMenu.classList.remove('show')}})}}
function initAOS(){if(typeof AOS!=='undefined'){AOS.init({duration:1000,once:!0})}}
function initGalleryPopup(){const galleryImages=safeQuerySelectorAll('.gallery-image');const popup=safeQuerySelector('#image-popup');const popupImg=safeQuerySelector('.popup-img');const popupClose=safeQuerySelector('.popup-close');galleryImages.forEach(img=>{img.addEventListener('click',()=>{if(popup&&popupImg){popup.style.display='flex';popupImg.src=img.src}})});if(popupClose){popupClose.addEventListener('click',()=>{if(popup)popup.style.display='none'})}
if(popup){popup.addEventListener('click',(e)=>{if(e.target===popup)popup.style.display='none'})}}
function initShowMore(){document.querySelectorAll('.show-more-btn').forEach((button)=>{button.addEventListener('click',()=>{const section=button.closest('.gallery-section');const hiddenImages=section.querySelectorAll('.gallery-list .gallery-item:nth-child(n+5)');const scrollPosition=window.pageYOffset||document.documentElement.scrollTop;hiddenImages.forEach(img=>(img.style.display='block'));button.disabled=!0;window.scrollTo({top:scrollPosition,behavior:'auto'})})})}
function initScrollManagement(){const restoreScrollPosition=()=>{const scrollPos=parseInt(sessionStorage.getItem("scrollPos"),10);if(!isNaN(scrollPos)){const maxScroll=document.documentElement.scrollHeight-window.innerHeight;window.scrollTo({top:Math.min(scrollPos,maxScroll),behavior:'auto'})}};const saveScrollPosition=()=>{sessionStorage.setItem("scrollPos",window.scrollY)};window.addEventListener("load",()=>{const loader=safeQuerySelector("#loader");if(loader){loader.style.transition="opacity 0.5s ease";loader.style.opacity=0;setTimeout(()=>{loader.style.display="none"},500)}
restoreScrollPosition();document.body.style.visibility="visible";initAOS()});window.addEventListener("beforeunload",()=>{saveScrollPosition()})}
function init(){initMobileMenu();initDropdown();initGalleryPopup();initShowMore();initScrollManagement();initAOS()}
document.addEventListener("DOMContentLoaded",init)